[workspace]
members = [
    "src/instance",
    "bin/tool",
    "src/on_browser_builder"
]
resolver = "2"

[patch."https://github.com/ClankPan/Vectune"]
vectune = {path = "../vectune"}

[patch."https://github.com/ClankPan/ssd-vectune"]
ssd-vectune = {path = "../ssd-vectune"}