[package]
name = "uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.37.0", features = ["full"] }
ic-agent = "0.36.0"
candid = "0.10.8"
dirs = "5.0.0"
bitvec = { version = "1.0.1", features = ["serde"]}
serde = { version =  "1.0", features = ["derive"] }
bincode = "1.3"
futures = "0.3"
memmap2 = "0.9.4"
bytesize = "1.3.0"
ssd-vectune = {path = "../../../ssd-vectune", features = []}
clap = { version = "4.5.4", features = ["derive"] }
rand = { version = "0.8", features = ["small_rng"] }
vectune = {path = "../../../vectune", features = []}